version: "3.8"
services:
  api:
    image: ${API_IMAGE}
    environment:
      - APP_ENV=local
      - APP_KEY=base64:J04Sul7y3S+xQsazDxWmeZ3L8TZA2YA5Ol7I3g1J90o=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_devops
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_started
  
  migrate:
    image: ${API_IMAGE}
    environment:
      - APP_ENV=local
      - APP_KEY=base64:J04Sul7y3S+xQsazDxWmeZ3L8TZA2YA5Ol7I3g1J90o=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_devops
      - DB_USERNAME=root
      - DB_PASSWORD=password
    command: sh -c "php artisan migrate --force"
    depends_on:
      mysql:
        condition: service_healthy


  mysql:
    image: mysql:8.0.21
    environment:
      - MYSQL_DATABASE=laravel_devops
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3



