apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: johnliutw/laravel-devops-api:20f803b6d0343442e42364ef408e65da5fce92c0
          command: ["sh", "-c", "php artisan migrate --force"]
          envFrom:
            - configMapRef:
                name: blog
            - secretRef:
                name: blog
          